const MOCK_CASES = [
    {
        radicado: "FPQRS-2026-04758",
        fechaRad: "07/05/2026",
        tipo: "Felicitación",
        tipoBadge: "bg-emerald-50 text-emerald-700 border border-emerald-200",
        servicio: "Atención al Asociado",
        categoria: "Atención Presencial",
        subcategoria: "Felicitación por excelente atención",
        asociado: "Sandra Milena Aguirre Torres",
        responsable: "Valentina Ospina Ríos",
        prioridad: "Baja",
        prioridadClass: "priority-baja",
        estado: "Cerrado",
        estadoClass: "status-cerrado",
        limiteSla: "09/05/2026",
        semaforo: "Cerrado",
        semaforoClass: "sla-grey",
        dotColor: "#94a3b8"
    },
    {
        radicado: "FPQRS-2026-04290",
        fechaRad: "07/05/2026",
        tipo: "Sugerencia",
        tipoBadge: "bg-purple-50 text-purple-700 border border-purple-200",
        servicio: "Pagos y Transferencias",
        categoria: "Transferencias Nacionales",
        subcategoria: "Comprobante de transferencia",
        asociado: "Yolanda Cecilia Prada Niño",
        responsable: "Jorge Iván Castillo",
        prioridad: "Baja",
        prioridadClass: "priority-baja",
        estado: "Radicado",
        estadoClass: "status-radicado",
        limiteSla: "08/05/2026",
        semaforo: "En tiempo",
        semaforoClass: "sla-green",
        dotColor: "#10b981"
    },
    {
        radicado: "FPQRS-2026-04760",
        fechaRad: "07/05/2026",
        tipo: "Queja",
        tipoBadge: "bg-amber-50 text-amber-700 border border-amber-200",
        servicio: "Canales Digitales",
        categoria: "App Móvil",
        subcategoria: "Falla de pasarela de pagos",
        asociado: "Andrés Camilo Rojas Velandia",
        responsable: "Iván Darío Zapata",
        prioridad: "Alta",
        prioridadClass: "priority-alta",
        estado: "En Proceso",
        estadoClass: "status-proceso",
        limiteSla: "12/05/2026",
        semaforo: "Por vencer",
        semaforoClass: "sla-orange",
        dotColor: "#f59e0b"
    }
];