const MOCK_CASES = [
    {
        radicado: "FPQRS-2026-04758",
        fechaRad: "07/05/2026",
        tipo: "Felicitación",
        servicio: "Atención al Asociado",
        categoria: "Atención Presencial",
        subcategoria: "Felicitación por excelente atención",
        asociado: "Sandra Milena Aguirre Torres",
        responsable: "Valentina Ospina Ríos",
        prioridad: "Baja",
        estado: "Cerrado",
        limiteSla: "09/05/2026",
        semaforo: "Cerrado"
    },
    {
        radicado: "FPQRS-2026-04290",
        fechaRad: "07/05/2026",
        tipo: "Sugerencia",
        servicio: "Pagos y Transferencias",
        categoria: "Transferencias Nacionales",
        subcategoria: "Comprobante de transferencia",
        asociado: "Yolanda Cecilia Prada Niño",
        responsable: "Jorge Iván Castillo",
        prioridad: "Baja",
        estado: "Radicado",
        limiteSla: "08/05/2026",
        semaforo: "En tiempo"
    },
    {
        radicado: "FPQRS-2026-04760",
        fechaRad: "07/05/2026",
        tipo: "Queja",
        servicio: "Canales Digitales",
        categoria: "App Móvil",
        subcategoria: "Sugerencia de nueva funcionalidad en app",
        asociado: "Andrés Camilo Rojas Velandia",
        responsable: "Iván Darío Zapata",
        prioridad: "Alta",
        estado: "Radicado",
        limiteSla: "12/05/2026",
        semaforo: "En tiempo"
    },
    {
        radicado: "FPQRS-2026-04350",
        fechaRad: "05/05/2026",
        tipo: "Sugerencia",
        servicio: "Ahorro y Captación",
        categoria: "Ahorro Programado",
        subcategoria: "Inconformidad con rendimientos",
        asociado: "Andrés Camilo Rojas Velandia",
        responsable: "Camilo Ernesto Herrera",
        prioridad: "Baja",
        estado: "Radicado",
        limiteSla: "08/05/2026",
        semaforo: "En tiempo"
    },
    {
        radicado: "FPQRS-2026-04782",
        fechaRad: "05/05/2026",
        tipo: "Reclamo",
        servicio: "Crédito",
        categoria: "Crédito de Consumo",
        subcategoria: "Descuento no reconocido en cuota",
        asociado: "Hernán Darío Quintero Salazar",
        responsable: "Carlos Andrés Moreno",
        prioridad: "Alta",
        estado: "En Gestión",
        limiteSla: "06/05/2026",
        semaforo: "Vencido"
    },
    {
        radicado: "FPQRS-2026-04115",
        fechaRad: "05/05/2026",
        tipo: "Sugerencia",
        servicio: "Atención al Asociado",
        categoria: "Atención Presencial",
        subcategoria: "Demora en trámite de documentos",
        asociado: "Inversiones Pacífico Ltda.",
        responsable: "Hernando José Pedraza",
        prioridad: "Baja",
        estado: "Radicado",
        limiteSla: "10/05/2026",
        semaforo: "En tiempo"
    },
    {
        radicado: "FPQRS-2026-04783",
        fechaRad: "05/05/2026",
        tipo: "Petición",
        servicio: "Crédito",
        categoria: "Crédito de Consumo",
        subcategoria: "Certificado de crédito vigente",
        asociado: "María Alejandra Cárdenas López",
        responsable: "Carlos Andrés Moreno",
        prioridad: "Normal",
        estado: "Asignado",
        limiteSla: "08/05/2026",
        semaforo: "En tiempo"
    },
    {
        radicado: "FPQRS-2026-04779",
        fechaRad: "04/05/2026",
        tipo: "Queja",
        servicio: "Pagos y Transferencias",
        categoria: "Pago PSE",
        subcategoria: "Pago PSE no acreditado en destino",
        asociado: "Jorge Luis Patiño Restrepo",
        responsable: "Rodrigo Esteban Muñoz",
        prioridad: "Crítica",
        estado: "Pendiente de Información",
        limiteSla: "05/05/2026",
        semaforo: "Vencido"
    },
    {
        radicado: "FPQRS-2026-04745",
        fechaRad: "04/05/2026",
        tipo: "Reclamo",
        servicio: "Crédito",
        categoria: "Crédito de Consumo",
        subcategoria: "Error en tasa de interés aplicada",
        asociado: "Luis Fernando Ospina Gómez",
        responsable: "Diana Carolina Ríos",
        prioridad: "Alta",
        estado: "En Gestión",
        limiteSla: "05/05/2026",
        semaforo: "Vencido"
    },
    {
        radicado: "FPQRS-2026-03870",
        fechaRad: "04/05/2026",
        tipo: "Sugerencia",
        servicio: "Canales Digitales",
        categoria: "App Móvil",
        subcategoria: "Sugerencia de nueva funcionalidad en app",
        asociado: "María Alejandra Cárdenas López",
        responsable: "Iván Darío Zapata",
        prioridad: "Baja",
        estado: "Radicado",
        limiteSla: "09/05/2026",
        semaforo: "En tiempo"
    },
    {
        radicado: "FPQRS-2026-03765",
        fechaRad: "03/05/2026",
        tipo: "Sugerencia",
        servicio: "Crédito",
        categoria: "Crédito de Consumo",
        subcategoria: "Tabla de amortización",
        asociado: "Jorge Luis Patiño Restrepo",
        responsable: "Carlos Andrés Moreno",
        prioridad: "Baja",
        estado: "Radicado",
        limiteSla: "08/05/2026",
        semaforo: "En tiempo"
    },
    {
        radicado: "FPQRS-2026-04730",
        fechaRad: "03/05/2026",
        tipo: "Queja",
        servicio: "Canales Digitales",
        categoria: "App Móvil",
        subcategoria: "Error de inicio de sesión en app",
        asociado: "Jean Pierre Dubois",
        responsable: "Luisa Fernanda Vargas",
        prioridad: "Normal",
        estado: "Pendiente de Información",
        limiteSla: "04/05/2026",
        semaforo: "Vencido"
    },
    {
        radicado: "FPQRS-2026-04771",
        fechaRad: "02/05/2026",
        tipo: "Reclamo",
        servicio: "Pagos y Transferencias",
        categoria: "Transferencias Nacionales",
        subcategoria: "Transferencia rechazada",
        asociado: "Construcciones Andinas S.A.S.",
        responsable: "Jorge Iván Castillo",
        prioridad: "Crítica",
        estado: "Respondido",
        limiteSla: "02/05/2026",
        semaforo: "Vencido"
    }
];